#!/bin/bash
# vim:set ai sts=4 ts=4 sw=4 expandtab filetype=sh:

set -e

MY_DIR="$( dirname "${0}" )"
if [ "${MY_DIR}" == "." ]; then
    MY_DIR="${PWD}"
fi

DEB_DIR="catkin"
ROS_REL="ros-indigo"

PACK_STAGE="${1:-stage1}"
DEPS_REGEX='.*/\(appctl\|onboard\)/.*'
REGEX_MOD=''

if [ "${PACK_STAGE,,}" = "stage2" ]; then
    REGEX_MOD='!'
fi

for pkg_able in `find "${MY_DIR}/${DEB_DIR}" -type f -path '*/debian/rules' ${REGEX_MOD} -iregex "${DEPS_REGEX}"`; do
    pkg_dir="$( dirname $( dirname $pkg_able ) )"
    pkg_name="$( basename ${pkg_dir} )"
    pkg_ver="$( dpkg-parsechangelog -l${pkg_dir}/debian/changelog --show-field Version | cut -d'-' -f1 )"
    #echo "pkg_dir: $pkg_dir, pkg_name: $pkg_name, pkg_ver: $pkg_ver" && continue # debugging
    tar -C ${pkg_dir}/.. \
        --exclude='*/.git' \
        --exclude='*/data/*.npz' \
        --exclude="*/debian/${ROS_REL}-*" \
        --exclude='*/obj-*-linux-gnu' \
        -czvvf ${pkg_dir}/../${ROS_REL}-$( echo ${pkg_name} | tr '_' '-' )_${pkg_ver}.orig.tar.gz \
        ./${pkg_name}
    pushd ${pkg_dir}
    dpkg-buildpackage -uc -us
    popd
    if [ "${PACK_STAGE,,}" = "stage1" ]; then
        sudo dpkg -i ${pkg_dir}/../${ROS_REL}-$( echo ${pkg_name} | tr '_' '-' )_${pkg_ver}*.deb
    fi
done

if [ "${PACK_STAGE,,}" = "stage1" ]; then
    exec ${0} stage2
fi
