#!/usr/bin/env bash

set -e

DIR=$( dirname "${BASH_SOURCE[0]}" )
cd $DIR
DIR=`pwd`

BUILD=lg-ros-build
SRCDIR=$DIR/src
DEBDIR=$DIR/debs

rm -rf $DEBDIR
mkdir -p $DEBDIR
cd $DEBDIR

# sudo rosdep init || /bin/true
# rosdep update
# sudo rosdep install -y --from-paths $SRCDIR --ignore-src \
#    --rosdistro=indigo --os=ubuntu:bionic

$BUILD $SRCDIR/appctl_msg_defs
sudo dpkg --force-overwrite -i ros-melodic-appctl-msg-defs_*bionic_*.deb
$BUILD $SRCDIR/appctl
